AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Create a periodic email report of temperature level for all devices with a temperature sensor in a SmartThings account

Parameters:
  SmartThingsAPIKey:
    Type: String
    Description: The SmartThings API Key.
  Schedule:
    Type: String
    Default: rate(1 day)
    Description: A CloudWatch Event Schedule Expression at which to invoke this function; see http://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html.
  FromAddress:
    Type: String
    Description: The email used to sent the report from.
  ToAddress:
    Type: String
    Description: The email address where the report will be sent.
  TemperatureUnit:
    Type: String
    Default: F
    Description: "Temperature unit: F or C (Fahrenheit or Celsius)"
  LowTemperatureLimit:
    Type: Number
    Default: 40
    Description: The low temperature limit (sensor with a value lower than this limit will be grouped together in the report)
  HighTemperatureLimit:
    Type: Number
    Default: 80
    Description: The high temperature limit (sensor with a value lower than this limit will be grouped together in the report)

Resources:
  TemperatureLevelReportFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: temperature_reports.temperature_measurement.lambda_handler
      Runtime: python3.6
      Timeout: 300
      CodeUri: ../../dist/smart-things-serverless-0.1.zip
      Environment:
        Variables:
          AUTHZ_TOKEN: !Ref SmartThingsAPIKey
          FROM_ADDRESS: !Ref FromAddress
          TO_ADDRESS: !Ref ToAddress
          TEMPERATURE_UNIT: !Ref TemperatureUnit
          LOW_TEMPERATURE_LIMIT: !Ref LowTemperatureLimit
          HIGH_TEMPERATURE_LIMIT: !Ref HighTemperatureLimit
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: !Ref Schedule
      Policies:
        -
          SESCrudPolicy:
            IdentityName: !Ref FromAddress
        -
          SESCrudPolicy:
            IdentityName: !Ref ToAddress
